// app/layout.tsx or app/layout.ts
import type { Metadata } from "next";
import "./globals.css";
import { GlobalHeader } from "@/app/components/GlobalHeader";
import { Footer } from "@/app/components/Footer";
import { FontLoader } from "@/app/components/FontLoader";
import { UIProvider } from "@/providers/ui-context";
import { fetchFooter, fetchHeader, fetchThemeSettings } from "@/lib/frontspace/client";

export const metadata: Metadata = {
  title: "Östers IF",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch header, footer, and theme settings in parallel
  const [header, footer, themeSettings] = await Promise.all([
    fetchHeader(),
    fetchFooter(),
    fetchThemeSettings(),
  ]);

  return (
    <html lang="sv">
      <head>
        <meta name="robots" content="index" />
        <FontLoader themeSettings={themeSettings} />
      </head>
      <body className="antialiased bg-custom_dark_dark_red">
        <UIProvider>
          {header && <GlobalHeader header={header} />}
          <main>
            {children}
          </main>
          {footer && <Footer footer={footer} />}
        </UIProvider>
      </body>
    </html>
  );
}
